apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-crypto-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-crypto-producer
  template:
    metadata:
      labels:
        app: my-crypto-producer
    spec:
      containers:
      - name: my-k8s-container-crypto-producer
        image: jiawei016/crypto-price-collector-producer
