apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      component: my-kafka
  template:
    metadata:
      labels:
        component: my-kafka
    spec:
      containers:
        - name: my-k8s-container-kafka
          image: confluentinc/cp-kafka:latest
          ports:
            - containerPort: 9092
          env:
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zookeeper-service:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://my-kafka:29092,PLAINTEXT_HOST://my-kafka:9092"
          - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
            value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
          - name: KAFKA_INTER_BROKER_LISTENER_NAME
            value: "PLAINTEXT"
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_MIN_INSYNC_REPLICAS
            value: "1"