apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-postgres
  template:
    metadata:
      labels:
        app: my-postgres
    spec:
      containers:
        - name: my-k8s-container-postgres
          image: postgres:latest
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "P@ssword_123"
          ports:
          - containerPort: 5432
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
          - name: pgdata
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}