apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-redis
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - name: my-k8s-container-redis
        image: redis:latest
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: 100m
            memory: 256Mi