apiVersion: apps/v1
kind: Deployment
metadata:
  name: my_k8s_zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      component: my_zookeeper
  template:
    metadata:
      labels:
        component: my_zookeeper
    spec:
      containers:
        - name: my_k8s_container_zookeeper
          image: confluentinc/cp-zookeeper:latest
          env:
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
          - name: ZOOKEEPER_TICK_TIME
            value: "2000"
          ports:
          - containerPort: 2181
          resources:
            limits:
              cpu: 500m
              memory: 1Gi